name: Coverage

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Coverage monitor
      uses: slavcodev/coverage-monitor-action@1.1.0
      with:
        # The GITHUB_TOKEN secret.
        github_token: 00896afe89770e7ca6541c89c79ed1fc8a9a7920
        # Path to Clover XML file.
        clover_file: coverage/clover.xml
        # Whether check the coverage thresholds.
        check: true
        # Whether comment the coverage report.
        comment: true
        # Mark the build as unstable when coverage is less than this threshold.
        threshold_alert: 0
        # Warning when coverage is less than this threshold.
        threshold_warning: 90
        # A string label to differentiate this status from the status of other systems.
        status_context: Coverage Report
        # A string label to differentiate the comment posted by this action.
        comment_context: Coverage Report
        # A mode for comments, supported: `replace`, `update` or `insert`.
        comment_mode: replace
